# This is the name of the Django app that contains the global settings for your site.
app_name: asklet_site

# This is the name of the Apache site that will host your Django app.
default_site: asklet_site

# This the template used to retrieving your Django app settings.
settings_module: '%(app_name)s.settings'
